# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'StateMod Documentation'
nav:
- Home: index.md
- 1 - Acknowledgement: Acknowledgement/1.md
- 2 - Introduction: Introduction/2.md
- 3 - Model Description:
    - 3.1 - Stream Flow Allocation: ModelDescription/31.md
    - 3.2 - System Operation: ModelDescription/32.md
    - 3.3 - Model Application: ModelDescription/33.md
    - 3.4 - Daily Operations: ModelDescription/34.md
    - 3.5 - Variable Efficiency: ModelDescription/35.md
    - 3.6 - Demands: ModelDescription/36.md
    - 3.7 - Soil Moisture Accounting: ModelDescription/37.md
    - 3.8 - Wells: ModelDescription/38.md
    - 3.9 - Plans: ModelDescription/39.md
- 4 - Input Description:
    - 4.0 - Remarks: InputDescription/40.md
    - 4.1 - Response File (*.rsp): InputDescription/41.md
    - 4.2 - Control File (*.ctl): InputDescription/42.md
    - 4.3 - River Network File (*.rin): InputDescription/43.md
    - 4.4 - River Station File (*.ris): InputDescription/44.md
    - 4.4.1 - River Gage File (*.rig): InputDescription/44_1.md
    - 4.5 - Direct Diversion Station File (*.dds): InputDescription/45.md
    - 4.6 - Direct Diversion Right File (*.ddr): InputDescription/46.md
    - 4.7 - Instream Flow Station File File (*.ifs): InputDescription/47.md
    - 4.8 - Instream Flow Right File (*.ifr): InputDescription/48.md
    - 4.9 - Well Station File (*.wes): InputDescription/49.md
    - 4.10 - Well Right File (*.wer): InputDescription/410.md
    - 4.11 - Reservoir Station File (*.res): InputDescription/411.md
    - 4.12 - Reservoir Right File (*.rer): InputDescription/412.md
    - 4.13 - Operational File (*.opr): InputDescription/413.md
    - 4.13.1 - Reservoir to Instream Flow: InputDescription/4131.md
    - 4.13.2 - Reservoir to a Direct Flow or Reservoir or Carrier: InputDescription/4132.md
    - 4.13.3 - Reservoir to a Carrier: InputDescription/4133.md
    - 4.13.4 Reservoir Exchange to a Direct Flow: InputDescription/4134.md
    - 4.13.5 Reservoir Exchange to Storage: InputDescription/4135.md
    - 4.13.6 Paper Exchange Between Reservoir Accounts (Bookover): InputDescription/4136.md
    - 4.13.7 Reservoir to a Carrier by Exchange: InputDescription/4137.md
    - 4.13.8 Out-of-Priority Bookover: InputDescription/4138.md
    - 4.13.9 Release for Target Contents: InputDescription/4139.md
    - 4.13.10 General Reservoir Replacement: InputDescription/41310.md
    - 4.13.11 Carrier Right to a Ditch or Reservoir: InputDescription/41311.md
    - 4.13.12 Reoperate Water Rights: InputDescription/41312.md
    - 4.13.13 La Plata Compact (Index flow): InputDescription/41313.md
    - 4.13.14 Carrier with Constrained Demand: InputDescription/41314.md
    - 4.13.15 Interruptible Supply: InputDescription/41315.md
    - 4.13.16 Direct Flow Storage: InputDescription/41316.md
    - 4.13.17 Rio Grande Compact - Rio Grande: InputDescription/41317.md
    - 4.13.18 Rio Grande Compact - Conejos River: InputDescription/41318.md
    - 4.13.19 Split Channel Operations: InputDescription/41319.md
    - 4.13.20 San Juan Reservoir RIP Operation: InputDescription/41320.md
    - 4.13.21 Wells with Sprinkler Use: InputDescription/41321.md
    - 4.13.22 Soil Moisture Use: InputDescription/41322.md
    - 4.13.23 Downstream Call: InputDescription/41323.md
    - 4.13.24 Direct Flow Exchange: InputDescription/41324.md
    - 4.13.25 Direct Flow Bypass: InputDescription/41325.md
    - 4.13.26 Changed Water Right: InputDescription/41326.md
    - 4.13.27 Plan or Reservoir Use Direct: InputDescription/41327.md
    - 4.13.28 Plan or Reservoir Use by Exchange: InputDescription/41328.md
    - 4.13.29 Plan Spill: InputDescription/41329.md
    - 4.13.30 Reservoir Rediversion: InputDescription/41330.md
    - 4.13.31 Carrier to a Ditch or Reservoir with Reuse: InputDescription/41331.md
    - 4.13.32 Reuse Plan to a User Direct: InputDescription/41332.md
    - 4.13.33 Reuse Plan to a User by Exchange: InputDescription/41333.md
    - 4.13.34 Bookover with Reuse: InputDescription/41334.md
    - 4.13.35 Import to a Plan: InputDescription/41335.md
    - 4.13.36 Seasonal (Daily) Water Right: InputDescription/41336.md
    - 4.13.37 Augmentation Well: InputDescription/41337.md
    - 4.13.38 Out-of-Priority Diversion: InputDescription/41338.md
    - 4.13.39 Alternate Point Diversion: InputDescription/41339.md
    - 4.13.40 South Platte Compact: InputDescription/41340.md
    - 4.13.41 Storage with Special Limits: InputDescription/41341.md
    - 4.13.42 Plan Reset: InputDescription/41342.md
    - 4.13.43 In-Priority Supply: InputDescription/41343.md
    - 4.13.44 Recharge Well: InputDescription/41344.md
    - 4.13.45 Carrier with Transit Loss: InputDescription/41345.md
    - 4.13.46 Multiple Ownership: InputDescription/41346.md
    - 4.13.47 Accounting Plan Limits: InputDescription/41347.md
    - 4.13.48 Plan or Reservoir Reuse to a Plan - Direct: InputDescription/41348.md
    - 4.13.49 Plan or Reservoir Reuse to a Plan – Exchange: InputDescription/41349.md
    - 4.13.50 South Platte Compact Storage: InputDescription/41350.md
    - 4.13.51 Operating Rule Examples: InputDescription/41351.md
    - 4.14 Precipitation Data File (*.pra or *.prm): InputDescription/414.md 
    - 4.15 Evaporation Data File (*.eva or *.evm): InputDescription/415.md 
    - 4.16 Stream Flow File - Monthly (*.rim): InputDescription/416.md 
    - 4.17 Direct Flow Demand File - Monthly (*.ddm): InputDescription/417.md 
    - 4.18 Direct Flow Demand File - Annual (*.dda): InputDescription/418.md 
    - 4.19 Direct Flow Overwrite File - Monthly (*.ddo): InputDescription/419.md 
    - 4.20 Instream Flow Demand File - Monthly (*.ifm): InputDescription/420.md 
    - 4.21 Instream Flow Demand File - Annual (*.ifa): InputDescription/421.md 
    - 4.22 Well Demand - Monthly (*.wem): InputDescription/422.md 
    - 4.23 Delay Table File - Monthly (*.urm/*.dly): InputDescription/423.md 
    - 4.24 Reservoir Target Content File – Annual (*.tar): InputDescription/424.md 
    - 4.25 Historic Reservoir Content File - Monthly (*.eom): InputDescription/425.md 
    - 4.26 Base Flow File (*.rib): InputDescription/426.md 
    - 4.27 Historic Streamflow File - Monthly (*.rih): InputDescription/427.md 
    - 4.28 Historic Diversion File - Monthly (*.ddh): InputDescription/428.md 
    - 4.29 Historic Well Pumping File - Monthly (*.weh): InputDescription/429.md 
    - 4.30 San Juan Recovery Plan Sediment File (*.sjr): InputDescription/430.md 
    - 4.31 Irrigation Parameter Yearly Data File - Annual (*.ipy): InputDescription/431.md 
    - 4.32 Consumptive Water Requirement File - Monthly (*.ddc): InputDescription/432.md 
    - 4.33 Soil Moisture (StateCU Structure) File (*.str): InputDescription/433.md 
    - 4.34 Geographic Information File (*.gis): InputDescription/434.md 
    - 4.35 Output Request File (*.out): InputDescription/435.md 
    - 4.36 Streamflow File - Daily (*.rid): InputDescription/436.md 
    - 4.37 Direct Flow Demand File - Daily (*.ddd): InputDescription/437.md 
    - 4.38 Instream Flow Demand File - Daily (*.ifd): InputDescription/438.md 
    - 4.39 Well Demand File - Daily (*.wed): InputDescription/439.md 
    - 4.40 Reservoir Target Content File - Daily (*.tad): InputDescription/440.md 
    - 4.41 Irrigation Water Requirement File - Daily (*.ddx): InputDescription/441.md 
    - 4.42 Delay Table File - Daily (*.urd/*.dld): InputDescription/442.md 
    - 4.43 Historic Streamflow File - Daily (*.riy): InputDescription/443.md 
    - 4.44 Historic Diversion File - Daily (*.ddy): InputDescription/444.md 
    - 4.45 Historic Well Pumping File - Daily (*.wey): InputDescription/445.md 
    - 4.46 Historic Reservoir Content File - Daily (*.eoy): InputDescription/446.md 
    - 4.47 Downstream Call File (*.cal): InputDescription/447.md 
    - 4.48 Rio Grande Spill (*.xrg): InputDescription/448.md 
    - 4.49 Plan Data (*.pln): InputDescription/449.md 
    - 4.50 Augmentation Plan to Well Data (*.plw): InputDescription/450.md 
    - 4.51 Plan Return File (*.prf): InputDescription/451.md 
    - 4.52 Reservoir Return Flow File (*.rrf): InputDescription/452.md 
    - 4.53 Reach Data File (*.rch): InputDescription/453.md 
    - 4.54 Plan to Reservoir Recharge Data (*.plr): InputDescription/454.md 
- 5 - Output Description:
    - 5.0 - Remarks: OutputDescription/50.md
    - 5.1 - Base Flow Module Output Files: OutputDescription/51.md
    - 5.1.1 - Base Flow Information File (*.xbi): OutputDescription/511.md
    - 5.1.2 - Gaged Base Flow Estimate File (*.xbg): OutputDescription/512.md
    - 5.1.3 - Other Base Flow Files (*.xbm): OutputDescription/513.md
    - 5.2 - Simulate Module Output Files: OutputDescription/52.md
    - 5.2.1 - Stream Summary File (*.xdd): OutputDescription/521.md
    - 5.2.2 - Reservoir Summary File (*.xre): OutputDescription/522.md
    - 5.2.3 - Well Summary File (*.xwe): OutputDescription/523.md
    - 5.2.4 - Structure Summary File (*.xss): OutputDescription/524.md
    - 5.2.5 - Operation Summary File (*.xop): OutputDescription/525.md
    - 5.2.6 - Log File (*.log): OutputDescription/526.md
    - 5.2.7 - Check File (*.chk): OutputDescription/527.md
    - 5.2.8 - Replacement Reservoir File (*.xrp): OutputDescription/528.md
    - 5.2.9 - Plan Summary File (*.xpl): OutputDescription/529.md
    - 5.2.9.1 - Term and Condition Plan (type 1): OutputDescription/5291.md
    - 5.2.9.2 - Well Augmentation Plan (type 2 and 10): OutputDescription/5292.md
    - 5.2.9.3 - Reservoir Reuse Plan (type 3): OutputDescription/5293.md
    - 5.2.9.4 - Non Reservoir Reuse Plan (type 4): OutputDescription/5294.md
    - 5.2.9.5 - Out-of-Priority Plan (type 9): OutputDescription/5295.md
    - 5.2.9.6 - Accounting Plan (type 11): OutputDescription/5296.md
    - 5.2.9.7 - Release Limit Plan (type 12): OutputDescription/5297.md
    - 5.2.9.8 - Changed Water Right Plan (type 13): OutputDescription/5298.md
    - 5.2.10 - Other Simulation Files (*.xir), (*.xdy), (*.xry), (*.xwy), (*.xpl): OutputDescription/5210.md
    - 5.3 - Report Module Output Files: OutputDescription/53.md
    - 5.3.1 - Basin Water Balance (*.xwb): OutputDescription/531.md
    - 5.3.2 - Water Right Report (*.xwr): OutputDescription/532.md
    - 5.3.3 - Additional Output Reports: OutputDescription/533.md
    - 5.4 - Data Check Output Files: OutputDescription/54.md
    - 5.5 - Binary Output Files: OutputDescription/55.md
    - 5.5.1 - Monthly Binary Direct Diversion File (*.b43): OutputDescription/551.md
    - 5.5.2 - Monthly Binary Reservoir File (*.b44): OutputDescription/552.md
    - 5.5.3 - Monthly Binary Well File (*.b42): OutputDescription/553.md
    - 5.5.4 - Daily Binary Direct Diversion File (*.b49): OutputDescription/554.md
    - 5.5.5 - Daily Binary Reservoir File (*.b50): OutputDescription/555.md
    - 5.5.6 - Daily Binary Well File (*.b65): OutputDescription/556.md
    - 5.6 - Additional Reporting Options: OutputDescription/56.md
    - 5.6.1 - Reach Reporting: OutputDescription/561.md
    - 5.6.2 - Detailed Call Data: OutputDescription/562.md
    - 5.6.3 - Call (Control) Reporting: OutputDescription/563.md
- 6 - Model Operation: ModelOperation/6.md
- 7 - Standard Modeling Procedures:
    - 7.1 - Running the Model: StandardModelingProcedures/71.md
    - 7.1.1 - Abnormal Model Termination: StandardModelingProcedures/71_1.md
    - 7.2 - Creating Natural Flows at Gages and Ungaged Locations: StandardModelingProcedures/72.md
    - 7.2.1 - Natural Flows with Recharge: StandardModelingProcedures/721.md
    - 7.2.2 - How to Check for Natural Flow Issues: StandardModelingProcedures/722.md
    - 7.3 - How to Simulate Soil Moisture Accounting and Variable Efficiency: StandardModelingProcedures/73.md
    - 7.3.1 - Soil Moisture Implementation: StandardModelingProcedures/731.md
    - 7.3.2 - Variable Efficiency: StandardModelingProcedures/732.md
    - 7.4 - How to Add or Change Modeled Input Data: StandardModelingProcedures/74.md
    - 7.4.1 - Change the Period of Record: StandardModelingProcedures/741.md
    - 7.4.2 - Add a Diversion Structure: StandardModelingProcedures/742.md
    - 7.4.3 - Add a Reservoir: StandardModelingProcedures/743.md
    - 7.4.4 - Add an Instream Flow Reach: StandardModelingProcedures/744.md
    - 7.4.5 - Add/Change a Water Right Priority or Amount: StandardModelingProcedures/745.md
    - 7.4.6 - Add/Change a Demand: StandardModelingProcedures/746.md
    - 7.4.7 - Demand Considerations: StandardModelingProcedures/747.md
    - 7.5 - How to Model Reservoir Operations: StandardModelingProcedures/75.md
    - 7.5.1 - Distribution of Reservoir Water Rights to Accounts: StandardModelingProcedures/751.md
    - 7.5.2 - Reservoir Release Operations: StandardModelingProcedures/752.md
    - 7.5.3 - General Replacement Reservoir Operations: StandardModelingProcedures/753.md
    - 7.5.4 - Re-distribute Reservoir Contents: StandardModelingProcedures/754.md
    - 7.5.5 - Reservoir Evaporation: StandardModelingProcedures/755.md
    - 7.5.6 - Reservoir Spills: StandardModelingProcedures/756.md
    - 7.5.7 - Reservoir Operations Troubleshooting: StandardModelingProcedures/757.md
    - 7.6 - How to Model Off-Channel Reservoir Systems: StandardModelingProcedures/76.md
    - 7.7 - How to Model Well Operations: StandardModelingProcedures/77.md
    - 7.7.1 - Add Supplemental Wells: StandardModelingProcedures/771.md
    - 7.7.2 - Add Groundwater Only Aggregate Structures: StandardModelingProcedures/772.md
    - 7.7.3 - Well Operational Considerations: StandardModelingProcedures/773.md
    - 7.7.4 - How to Implement the Maximum or Mutual Supply Approaches: StandardModelingProcedures/774.md
    - 7.8 - How to Model Plan Structures and Operations: StandardModelingProcedures/78.md
    - 7.9 - How to Model a Release Limit Plan: StandardModelingProcedures/79.md
    - 7.10 - How to Model Augmentation Plans: StandardModelingProcedures/710.md
    - 7.10.1 - Augmentation Plan Structure: StandardModelingProcedures/7101.md
    - 7.10.2 - Canal Loss (Seepage) as an Augmentation Supply: StandardModelingProcedures/7102.md
    - 7.10.3 - Reservoir Recharge (Seepage) as an Augmentation Supply: StandardModelingProcedures/7103.md
    - 7.10.4 - Augmentation or Recharge Well Pumping as an Augmentation Supply: StandardModelingProcedures/7104.md
    - 7.10.5 - Direct Reservoir Release as an Augmentation Supply: StandardModelingProcedures/7105.md
    - 7.10.6 - Special Well Augmentation Plans: StandardModelingProcedures/7106.md
    - 7.11 - How to Model Changed Water Rights and Return Flow Obligations: StandardModelingProcedures/711.md
    - 7.11.1 - Changed Water Right Plan Structure: StandardModelingProcedures/7111.md
    - 7.11.2 - Releases from a Changed Water Right Plan: StandardModelingProcedures/7112.md
    - 7.11.3 - Terms and Conditions Operations: StandardModelingProcedures/7113.md
    - 7.11.4 - Augmentation Station Modeling: StandardModelingProcedures/7114.md
    - 7.12 - How to Model Alternate Points/Exchanges: StandardModelingProcedures/712.md
    - 7.13 - How to Model Imported Water: StandardModelingProcedures/713.md
    - 7.14 - How to Model Reusable Supplies: StandardModelingProcedures/714.md
    - 7.15 - How to Implement a Futile Call: StandardModelingProcedures/715.md
    - 7.16 - Basin-Specific Operations and Compacts: StandardModelingProcedures/716.md
    - 7.16.1 - Blue River Decree (Upstream Storage and OOP Plans): StandardModelingProcedures/7161.md  
    - 7.16.2 - Rio Grande Compact: StandardModelingProcedures/7162.md  
    - 7.16.3 - South Platte Compact: StandardModelingProcedures/7163.md
    - 7.16.4 - La Plata Compact: StandardModelingProcedures/7164.md
    - 7.17 - How to Add Daily Capability: StandardModelingProcedures/717.md
    - 7.17.1 - Implementing Daily Model Capabilities in a Monthly Model: StandardModelingProcedures/7171.md
- 8 - Supporting Utilities:
    - 8.1 - Big Picture Plot: SupportingUtilities/81.md
    - 8.2 - Basin Linkage: SupportingUtilities/82.md
    - 8.3 - StateMod File Comparison: SupportingUtilities/83.md
    - 8.4 - StateDMI: SupportingUtilities/84.md
    - 8.5 - TSTool DMI: SupportingUtilities/85.md
    - 8.6 - StateCU: SupportingUtilities/86.md
    - 8.7 - SmNewRsp (StateMod Response File Program): SupportingUtilities/87.md
    - 8.8 - SmDelay (StateMod Delay File Program): SupportingUtilities/88.md
- 9 - Discontinued but Supported File Formats:
    - 9.1 - Response File (Sequential): Discontinued/91.md
    - 9.2 - Soil Moisture Parameter File (*.par): Discontinued/92.md
    - 9.3 - Irrigation Practice File (*.ipy): Discontinued/93.md
    - 9.4 - Operating Rule File (*.opr): Discontinued/94.md

# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon: 'images/DWR_icon.gif'
#theme: readthedocs
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenCDSS/cdss-app-statemod-fortran-doc-user
site_description:  'StateMod Documentation'
site_author:  'Colorado Department of Natural Resources'
copyright:  'Copyright Colorado Department of Natural Resources'
# Extra options
extra:
 #Use extra CSS to customize styles, based on theme
 extra_css: 'css/extra-material-theme.css'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
markdown_extensions:
  - mdx_math
  - footnotes